name: keep_it
description: An all allows you to preserve the images you get from web in an organized manner, without messing it up with photos.
publish_to: 'none' 
homepage: htts://www.cloudonlanapps.com

version: 0.1.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image: ^4.1.3
  flutter_riverpod: ^2.4.9
  colan_widgets:
    path: ../colan_widgets
  app_loader:
    path: ../app_loader
  store: 
    path: ../store
  logger: ^2.0.2+1
  go_router: ^12.1.1
  shared_preferences: ^2.2.2
  share_handler: ^0.0.18
  video_player: ^2.8.1
  sqlite3: ^2.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  collection: ^1.17.2
  palette_generator: ^0.3.3+3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  infinite_carousel: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/nature-sky-water-sea-natural-landscape-ocean-1520813-pxhere.com.jpg
    - assets/wallpaperflare.com_wallpaper-2.jpg
    - assets/wallpaperflare.com_wallpaper.jpg
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
